sudo: false
language: ruby
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
matrix:
  exclude:
    # Rails 4.0 and 4.1 doesn't support Ruby 2.4 (because of integer unification)
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4.1.gemfile
before_install: gem install bundler -v 1.14.6
